apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: jira-cicd
  labels:
    name: jira
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 8080
  selector:
    name: jira
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira
  namespace: jira-cicd
  labels:
    name: jira
spec:
  selector:
    matchLabels:
      name: jira
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: jira
    spec:
      containers:
      - image: atlassian/jira-software:latest
        name: jira
        env:
        - name: ALT_JDBC_URL
          value: jdbc:mysql://jira-mysql:3306/jiradb
        - name: ALT_JDBC_DRIVER
          value: com.mysql.jdbc.Driver
        - name: ALT_JDBC_USER
          value: root
        - name: ALT_DB_TYPE
          value: mysql
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-pv
      volumes:
      - name: jira-pv
        persistentVolumeClaim:
          claimName: jira-pvc