apiVersion: v1
kind: Service
metadata:
  name: jira-mysql
  namespace: jira-cicd
  labels: 
    name: jira
spec:
  ports:
    - port: 3306
  selector:
    name: jira
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jira-mysql
  namespace: jira-cicd
spec:
  selector:
    matchLabels:
      name: jira-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: jira-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jira-mysql-pass-cthtdk8tk9
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: jira-mysql-pv
          mountPath: var/lib/mysql
      volumes:
      - name: jira-mysql-pv
      persistentVolumeClaim:
          claimName: jira-mysql-pvc	